HelpDesk/Controllers/SolicitudServiciosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HelpDesk.Data;
using HelpDesk.Models;
using Microsoft.AspNetCore.Identity;

namespace HelpDesk.Controllers
{
    public class SolicitudServiciosController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public SolicitudServiciosController(ApplicationDbContext context,
                                             UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;

        }

        // GET: SolicitudServicios
        public async Task<IActionResult> Index()
        {
            return View(await _context.SolicitudServicio.ToListAsync());
        }

        public async Task<IActionResult> SolicitudSinAsignar()
        {
            return View(await (from s in _context.SolicitudServicio
                               where s.tecnicoAsig == null
                               select s).ToListAsync());
        }

        public async Task<IActionResult> AsignarTecnico(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var solicitudServicio = await _context.SolicitudServicio.SingleOrDefaultAsync(m => m.ID == id);
            solicitudServicio.getEstados(_context);
            solicitudServicio.getTecnico(_context);
            if (solicitudServicio == null)
            {
                return NotFound();
            }
            return View(solicitudServicio);
        }

        public async Task<IActionResult> AsignarOtroTecnico(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var solicitudServicio = await _context.SolicitudServicio.SingleOrDefaultAsync(m => m.ID == id);
            solicitudServicio.getEstados(_context);
            solicitudServicio.getTecnico(_context);
            if (solicitudServicio == null)
            {
                return NotFound();
            }
            return View(solicitudServicio);
        }

        public async Task<IActionResult> ServicioTecnico()
        {

            return View(await (
                               from x in _context.SolicitudServicio
                               where x.tecnicoAsig
                               == _userManager.GetUserName(User)
                               select x).ToListAsync());
        }



        // GET: SolicitudServicios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var solicitudServicio = await _context.SolicitudServicio
                .SingleOrDefaultAsync(m => m.ID == id);
            if (solicitudServicio == null)
            {
                return NotFound();
            }

            return View(solicitudServicio);
        }

        // GET: SolicitudServicios/Create
        public IActionResult Create()
        {
            SolicitudServicio solicitudServicio = new SolicitudServicio();
            solicitudServicio.getEstados(_context);
            solicitudServicio.getTecnico(_context);
            return View();
        }

        // POST: SolicitudServicios/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Solicitante,FechaSolicitud,Descripcion,estadoS,tecnicoAsig,comentarioAdicional,comentarioTareaCompleta")] SolicitudServicio solicitudServicio)
        {
            if (ModelState.IsValid)
            {
                _context.Add(solicitudServicio);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(solicitudServicio);
        }

        // GET: SolicitudServicios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var solicitudServicio = await _context.SolicitudServicio.SingleOrDefaultAsync(m => m.ID == id);
            solicitudServicio.getEstados(_context);
            solicitudServicio.getTecnico(_context);
            if (solicitudServicio == null)
            {
                return NotFound();
            }
            return View(solicitudServicio);
        }

        public async Task<IActionResult> ServicioCompletado(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var solicitudServicio = await _context.SolicitudServicio.SingleOrDefaultAsync(m => m.ID == id);
            solicitudServicio.getEstados(_context);
            solicitudServicio.getTecnico(_context);
            if (solicitudServicio == null)
            {
                return NotFound();
            }
            return View(solicitudServicio);
        }

        // POST: SolicitudServicios/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Solicitante,FechaSolicitud,Descripcion,estadoS,tecnicoAsig,comentarioAdicional,comentarioTareaCompleta")] SolicitudServicio solicitudServicio)
        {
            if (id != solicitudServicio.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(solicitudServicio);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SolicitudServicioExists(solicitudServicio.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(solicitudServicio);
        }

        // GET: SolicitudServicios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var solicitudServicio = await _context.SolicitudServicio
                .SingleOrDefaultAsync(m => m.ID == id);
            if (solicitudServicio == null)
            {
                return NotFound();
            }

            return View(solicitudServicio);
        }

        // POST: SolicitudServicios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var solicitudServicio = await _context.SolicitudServicio.SingleOrDefaultAsync(m => m.ID == id);
            _context.SolicitudServicio.Remove(solicitudServicio);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SolicitudServicioExists(int id)
        {
            return _context.SolicitudServicio.Any(e => e.ID == id);
        }
    }
}

HelpDesk/Controllers/UserDatasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HelpDesk.Data;
using HelpDesk.Models;
using Microsoft.AspNetCore.Identity;

namespace HelpDesk.Controllers
{
    public class UserDatasController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public UserDatasController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: UserDatas
        public async Task<IActionResult> Index()
        {
            return View(await _context.UserData.ToListAsync());
        }

        public async Task<IActionResult> ListarUsuarios()
        {
            return View(await _userManager.Users.ToListAsync());
        }

        // GET: UserDatas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userData = await _context.UserData
                .SingleOrDefaultAsync(m => m.ID == id);
            if (userData == null)
            {
                return NotFound();
            }

            return View(userData);
        }

        // GET: UserDatas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: UserDatas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Nombres,Apellidos,FechaNacimiento,Correo,Pass,Celular")] UserData userData)
        {
            if (ModelState.IsValid)
            {
                _context.Add(userData);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(userData);
        }

        // GET: UserDatas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userData = await _context.UserData.SingleOrDefaultAsync(m => m.ID == id);
            if (userData == null)
            {
                return NotFound();
            }
            return View(userData);
        }

        // POST: UserDatas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Nombres,Apellidos,FechaNacimiento,Correo,Pass,Celular")] UserData userData)
        {
            if (id != userData.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(userData);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserDataExists(userData.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(userData);
        }

        // GET: UserDatas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userData = await _context.UserData
                .SingleOrDefaultAsync(m => m.ID == id);
            if (userData == null)
            {
                return NotFound();
            }

            return View(userData);
        }

        // POST: UserDatas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var userData = await _context.UserData.SingleOrDefaultAsync(m => m.ID == id);
            _context.UserData.Remove(userData);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserDataExists(int id)
        {
            return _context.UserData.Any(e => e.ID == id);
        }
    }
}

HelpDesk/Views/Shared/_Layout.cshtml
@inject SignInManager<ApplicationUser> SignInManager
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HelpDesk</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">ABC</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (SignInManager.IsSignedIn(User))
                    {
                        @if (User.IsInRole("Administrador"))
                        {
                            <li><a asp-area="" asp-controller="UserDatas" asp-action="Index">Lista de Usuarios</a></li>
                            <li><a asp-area="" asp-controller="SolicitudServicios" asp-action="Index">Solicitudes Asignadas</a></li>
                            <li><a asp-area="" asp-controller="SolicitudServicios" asp-action="SolicitudSinAsignar">Solicitudes Sin Asignar</a></li>
                            <li><a asp-area="" asp-controller="Account" asp-action="Register">Registrar Usuario</a></li>
                        }
                        @if (User.IsInRole("Tecnico"))
                        {
                            <li><a asp-area="" asp-controller="SolicitudServicios" asp-action="ServicioTecnico">Mis Asignaciones</a></li>
                        }
                        @if (User.IsInRole("Usuario"))
                        {
                            <li><a asp-area="" asp-controller="SolicitudServicios" asp-action="Index">Solicitudes de Servicios</a></li>
                        }
                    }
                    else
                    {
                        <li><a asp-area="" asp-controller="Home" asp-action="Index">Inicio</a></li>
                        <li><a asp-area="" asp-controller="Account" asp-action="Register">Registrar Usuario</a></li>
                    }

                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - HelpDesk</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>